ingInventario/Models/Marca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ingInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int id_marca { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}

ingInventario/Controllers/MarcasController.cs
using ingInventario.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ingInventario.Controllers
{
    public class MarcasController : Controller
    {
        private inventariodbEntities db = new inventariodbEntities();
        ///método para cargar lista de marcas (get)
        public ActionResult Index()
        {
            //select * from Marca
            var marcas = db.Marca.ToList();
            return View(marcas);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Marca marca)
        {
            if (ModelState.IsValid)
            {
                //guardar en base de datos
                //insert into marca (nombre, descripcion) values ('pepsi', 'bebida')
                db.Marca.Add(marca);
                db.SaveChanges();// guardar cambios
                return View();
            }
            return View(marca);
        }
        public ActionResult Edit(int? id)
        {
            //si crea en una página aparte enviará el error 404
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //buscar el id en la marca: SELECT * FROM Marca WHERE id_marca = id;
            Marca marca = db.Marca.Find(id);//Find busca sólo el id que correspanda 
            //retornar el nombre _Edit, 
            return PartialView("_Edit",marca);
        }
        [HttpPost]
        public ActionResult Edit(Marca marca)
        {
            //edita los datos de la marca seleccionado
            //(update marca set nombre = marca.nombre, descripcion = marca.descripcion where id_marca = marca.id_marca)
            db.Entry(marca).State = EntityState.Modified;
            //guarda los cambios en la base de datos
            db.SaveChanges();
            return RedirectToAction("Index");//retorna la vista Index(lista de marcas)
        }
        public ActionResult Delete(int? id)
        {
            if(id != null)
            {
                var marca = db.Marca.Find(id);//Find, WHERE, First, FirstOrDefault
                return PartialView("_Delete", marca);
            }
            return View();
        }
        [HttpPost]
        public ActionResult Delete(int id_marca)
        {
            var marca = db.Marca.Find(id_marca);
            //eliminar con entity framework
            db.Marca.Remove(marca);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ingInventario/Views/Marcas/Create.cshtml
@{
    ViewBag.Title = "Crear Marca";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <h2>Crear Marca</h2>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <h3>Ingrese los datos de la marca a crear</h3>
            </div>
            <div class="ibox-content">
                <form method="post" action="/Marcas/Create">
                    <div class="form-group row">
                        <label class="col-2 text-right">Nombre:</label>
                        <div class="col-10">
                            <input type="text" name="nombre" id="nombre" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 text-right">Descripción:</label>
                        <div class="col-10">
                            <input type="text" name="descripcion" class="form-control" />
                        </div>
                    </div>
                    <div class="text-center">
                        <input type="submit" value="Guardar" id="guardar" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script>
    $('#guardar').click(function (e) {
        if ($('#nombre').val().trim() == '') {
            alert('Ingrese nombre');
            e.preventDefault();
        }
    });
</script>

ingInventario/Views/Marcas/Index.cshtml
@model IEnumerable<ingInventario.Models.Marca>
@{
    ViewBag.Title = "Index";
}
<div class="row wrapper border-bottom white-bg page-heading">
    <h2>Gestionar Marcas</h2>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <h2>Lista de marcas</h2>
            </div>
            <div class="ibox-content">
                <table class="table table-striped table-bordered" id="tabla">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.id_marca</td>
                                <td>@item.nombre</td>
                                <td>@item.descripcion</td>
                                <td>
                                    <button class="btn btn-warning" data-toggle="modal"
                                            data-url="@Url.Action("Edit","Marcas",new { id = item.id_marca })">
                                        Editar
                                    </button>
                                    <input type="button" class="btn btn-danger" data-toggle="modal"
                                           data-url="@Url.Action("Delete","Marcas", new { id = item.id_marca })" value="Eliminar" />
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalEdit">
    <!-- EN ESTA PARTE SE CARGARÁ LA VISTA PARCIAL-->
</div>
<div class="modal fade" id="modalDelete">
    <!-- EN ESTA PARTE SE CARGARÁ LA VISTA PARCIAL DEL ELIMINAR-->
</div>
<link href="~/Content/plugins/dataTables/datatables.min.css" rel="stylesheet" />
<script src="~/Scripts/plugins/dataTables/datatables.min.js"></script>
<script src="~/Scripts/plugins/dataTables/dataTables.bootstrap4.min.js"></script>
<script>
    //# accedo a los elementos por id,
    //. accede a los elementos por la clase
    $('.btn-warning').click(function () {
        let url = $(this).data('url');//se obtiene la url a la cual acceder y se accina a la variable url
        //get /Marca/Edit/1
        $.get(url, function (data) {
            $('#modalEdit').html(data);
            $('#modalEdit').modal('show');
        });
    });
    $('#tabla').DataTable({
        pageLength: 25,
        dom: '<"html5buttons"B>lTfgitp',
        buttons: [
            { extend: 'excel', title: 'Marcas', exportOptions: { modifier: { page: 'all', search: 'none' } } },
            {
                extend: 'pdf', title: 'Marcas', exportOptions: { modifier: { page: 'all', search: 'none' } }
            },

            {
                extend: 'print',
                text: 'Imprimir',
                messageTop: 'Sistema Inventario',
                customize: function (win) {
                    $(win.document.body).addClass('white-bg');
                    $(win.document.body).css('font-size', '10px');

                    $(win.document.body).find('table')
                        .addClass('compact')
                        .css('font-size', 'inherit');
                }
            }
        ],
        order: [[1, "desc"]],
        language:
        {
            sProcessing: "Procesando...",
            sLengthMenu: "Mostrar _MENU_ registros",
            sZeroRecords: "No se encontraron resultados",
            sEmptyTable: "Ningún dato disponible en esta tabla",
            sInfo: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            sInfoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
            sInfoFiltered: "(filtrado de un total de _MAX_ registros)",
            sInfoPostFix: "",
            sSearch: "Buscar:",
            sUrl: "",
            sInfoThousands: ",",
            sLoadingRecords: "Cargando...",
            oPaginate: {
                sFirst: "Primero",
                sLast: "Último",
                sNext: "Siguiente",
                sPrevious: "Anterior"
            },
            oAria: {
                sSortAscending: ": Activar para ordenar la columna de manera ascendente",
                sSortDescending: ": Activar para ordenar la columna de manera descendente"
            }
        }
    });

    //se accede a la clase del botón Eliminar
    $('.btn-danger').click(function () {
        let url = $(this).data('url');
        $.get(url, function (data) {
            $('#modalDelete').html(data);
            $('#modalDelete').modal('show');
        });
    });

</script>

ingInventario/Views/Marcas/_Delete.cshtml
@model ingInventario.Models.Marca
<div class="modal-dialog">
    <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">Eliminar Marca</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <form action="/Marcas/Delete" method="post">
            <!-- Modal body -->
            <div class="modal-body">
                <input type="hidden" name="id_marca" value="@Model.id_marca" />
               <h2>¿Desea eliminar la marca @Model.nombre ?</h2>
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                <input type="submit" value="Eliminar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

ingInventario/Views/Marcas/_Edit.cshtml
@model ingInventario.Models.Marca
<div class="modal-dialog">
    <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
            <h4 class="modal-title">Detalle Marca</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <form action="/Marcas/Edit" method="post">
            <!-- Modal body -->
            <div class="modal-body">
                <input type="hidden" name="id_marca" value="@Model.id_marca" />
                <label> Nombre:</label>
                <input type="text" name="nombre" value="@Model.nombre" class="form-control" />
                <label>Descripción:</label>
                <input type="text" name="descripcion" value="@Model.descripcion" class="form-control" />
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>