ingInventario/Controllers/ProveedoresController.cs
using ingInventario.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ingInventario.Controllers
{
    public class ProveedoresController : Controller
    {
        private inventariodbEntities db = new inventariodbEntities();
        // GET: Proveedores
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Proveedor proveedor)
        {
            db.Proveedor.Add(proveedor);
            db.SaveChanges();
            return View();
        }

        public ActionResult Index()
        {
            var proveedores = db.Proveedor.ToList();
            return View(proveedores);
        }
    }
}

ingInventario/Views/Proveedores/Create.cshtml
@{
    ViewBag.Title = "Crear Proveedor";
}


<div class="row wrapper border-bottom white-bg page-heading">
    <h2>Crear Proveedor</h2>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <h3>Ingrese los datos del proveedor a crear</h3>
            </div>
            <div class="ibox-content">
                <form method="post" action="@Url.Action("Create","Proveedores")">
                    <div class="form-group row">
                        <label class="col-2 text-right">Run:</label>
                        <div class="col-10">
                            <input type="text" name="rut" id="rut" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 text-right">Nombre:</label>
                        <div class="col-10">
                            <input type="text" name="nombre" id="nombre" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 text-right">Teléfono:</label>
                        <div class="col-10">
                            <input type="text" name="fono" id="fono" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 text-right">Email:</label>
                        <div class="col-10">
                            <input type="email" name="email" id="email" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-2 text-right">Email:</label>
                        <div class="col-10">
                            <textarea name="comentario" id="comentario" class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="text-center">
                        <input type="submit" value="Guardar" id="guardar" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
  
</script>

ingInventario/Views/Proveedores/Index.cshtml
@model IEnumerable<ingInventario.Models.Proveedor>
@{
    ViewBag.Title = "Index";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <h2>Gestionar Proveedores</h2>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <h2>Lista de proveedores</h2>
            </div>
            <div class="ibox-content">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Run</th>
                            <th>Nombre</th>
                            <th>Teléfono</th>
                            <th>Email</th>
                            <th>Comentario</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.rut</td>
                                <td>@item.nombre</td>
                                <td>@item.fono</td>
                                <td>@item.email</td>
                                <td>@item.comentario</td>
                                <td>
                                    <button class="btn btn-warning" data-toggle="modal"
                                            data-url="@Url.Action("Edit","Proveedores",new { id = item.id_proveedor })">
                                        <i class="fa fa-edit"> </i>
                                    </button>
                                    <button class="btn btn-danger" data-toggle="modal"
                                            data-url="@Url.Action("Delete","Proveedores", new { id = item.id_proveedor })">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalEdit">
    <!-- EN ESTA PARTE SE CARGARÁ LA VISTA PARCIAL-->
</div>
<div class="modal fade" id="modalDelete">
    <!-- EN ESTA PARTE SE CARGARÁ LA VISTA PARCIAL DEL ELIMINAR-->
</div>
<script>
    //# accedo a los elementos por id,
    //. accede a los elementos por la clase
    $('.btn-warning').click(function () {
        let url = $(this).data('url');//se obtiene la url a la cual acceder y se accina a la variable url
        //get /Marca/Edit/1
        $.get(url, function (data) {
            $('#modalEdit').html(data);
            $('#modalEdit').modal('show');
        });
    });
    //se accede a la clase del botón Eliminar
    $('.btn-danger').click(function () {
        let url = $(this).data('url');
        $.get(url, function (data) {
            $('#modalDelete').html(data);
            $('#modalDelete').modal('show');
        });
    });

</script>