ingInventario/Models/OrdenEntrada.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ingInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenEntrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenEntrada()
        {
            this.DetalleEntrada = new HashSet<DetalleEntrada>();
        }
    
        public int id_orden { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_user { get; set; }
        public string comentario { get; set; }
        public int num_factura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEntrada> DetalleEntrada { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}

ingInventario/Controllers/OrdenEntradasController.cs
using ingInventario.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ingInventario.Controllers
{
    [OutputCache(VaryByCustom = "*", Duration = 0)]
    public class OrdenEntradasController : Controller
    {
        private inventariodbEntities db = new inventariodbEntities();
        // GET: OrdenEntradas
        public ActionResult OrdenEntrada()
        {
            return View();
        }
        [HttpPost]
        public JsonResult OrdenEntrada(OrdenEntrada orden, List<DetalleEntrada> detalles)
        {
            //primer necesitamos gurdar orden de entrada
            orden.fecha = DateTime.Now;//añade la fecha de hoy a OrdenEntrada
            orden.id_user = 1;//añade el id al usuario que esta en base
            db.OrdenEntrada.Add(orden);
            db.SaveChanges();
            //capturar el id_orden autoincrementable
            var idDet = orden.id_orden;
            //se crea foreach para recorrer la lista de detalles(DetalleEntrada)
            foreach (var item in detalles)
            {
                //se añade al registro de productos(detalle) el id_orden
                item.id_orden = idDet;
                db.DetalleEntrada.Add(item);
                //actualizar stock del producto
                ActualizaStock(item.id_producto, item.cantidad);
                db.SaveChanges();
            }
            return Json("");
        }
        //método para actualizar el stock existente de producto
        public void ActualizaStock(int id_producto, int cantidad)
        {
            //verifica que el producto existe, según id
            var producto = db.Producto.Find(id_producto);
            //suma la nueva cantidad a la cantidad existente del producto
            producto.cantidad = producto.cantidad + cantidad;//producto.cantidad += cantidad;
            db.Entry(producto).State = EntityState.Modified;
        }
        [HttpPost]
        public ActionResult CodigoExiste(string codigo)
        {
            var q = db.Producto.FirstOrDefault(p => p.codigo.ToLower().Equals(codigo.ToLower()));
            if (q != null)
            {
                return Json(new { q.nombre, q.id_producto }, JsonRequestBehavior.AllowGet);
            }
            return Json("");
        }

        public ActionResult HistorialEntradas()
        {
            return View();
        }
        
        public ActionResult Ordenes(DateTime? inicio, DateTime? fin)
        {
            //consulta con las ordenes de entrada
            var orden = db.OrdenEntrada.ToList();
            if (inicio != null)
            {
                //filtro por fechas
                orden = orden.Where(o => o.fecha >= inicio && o.fecha <= fin).ToList();
            }
            //retornar la vista parcial y el modelo
            return PartialView("_Ordenes", orden);
        }

        //mostrar detalle de la orden
        public ActionResult DetalleOrden(int id)
        {
            var detalle = db.OrdenEntrada.Find(id);
            return View(detalle);
        }
    }
}

ingInventario/Views/OrdenEntradas/DetalleOrden.cshtml
@model ingInventario.Models.OrdenEntrada
@{
    ViewBag.Title = "DetalleOrden";
}


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <div class="form-group row">
                    <label class="col-2 text-right">N° Factura: </label>
                    <div class="col-sm-2">
                        <label>@Model.num_factura</label>
                    </div>
                    <label class="col-2 text-right">Usuario Ingreso: </label>
                    <div class="col-sm-2">
                        <label>@Model.Usuario.nombre</label>
                    </div>
                    <label class="col-2 text-right">Fecha Ingreso: </label>
                    <div class="col-sm-2">
                        <label>@Model.fecha.ToShortDateString()</label>
                    </div>
                </div>
            </div>
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped" >
                        <thead class="bg-primary">
                            <tr>
                                <th>Código Producto</th>
                                <th>Nombre</th>
                                <th>Cantidad</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.DetalleEntrada)
                            {
                                <tr>
                                    <td>@item.Producto.codigo</td>
                                    <td>@item.Producto.nombre</td>
                                    <td>@item.cantidad</td>                                    
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

ingInventario/Views/OrdenEntradas/HistorialEntradas.cshtml
@model IEnumerable<ingInventario.Models.OrdenEntrada>
@{
    ViewBag.Title = "HistorialEntradas";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <h2>Historial Ordedn de entradas</h2>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <div class="form-group row">
                    <label class="col-2 text-right">Rango Fechas </label>
                    <div class="col-sm-4">
                        <input type="text" id="fechas" name="fechas" class="form-control" />
                    </div>
                    <input type="button" class="btn btn-primary" id="buscar" value="Buscar" />
                </div>
            </div>
            <div class="ibox-content" id="listaOrdenes">

            </div>
        </div>
    </div>
</div>
<link href="~/Content/plugins/daterangepicker.css" rel="stylesheet" />
<script src="~/Scripts/plugins/moment.min.js"></script>
<script src="~/Scripts/plugins/daterangepicker.js"></script>
<script>
    //daterangepicker sirve para seleccionar un rango de fechas
    $('input[name="fechas"]').daterangepicker({
        autoUpdateInput: false,
        autoApply: true,
        maxDate: moment(),
        locale: {
            format: 'DD-MM-YYYY'
        }
    });
    $('input[name="fechas"]').on('apply.daterangepicker', function (ev, picker) {
        $(this).val(picker.startDate.format('DD-MM-YYYY') + ' hasta ' + picker.endDate.format('DD-MM-YYYY'));
    });
    $('#buscar').click(function () {
        //captura la fecha de inicio selecionada en el input
        let inicio = $('#fechas').data('daterangepicker').startDate.format('YYYY-MM-DD');
        //captura la fecha final selecionada en el input
        let fin = $('#fechas').data('daterangepicker').endDate.format('YYYY-MM-DD');
        //logica para enviar datos al controlador y traer respuesta
       
        let d = '?inicio=' + inicio + '&fin=' + fin;
        //get para retornar vista parcial
        $.get('@Url.Action("Ordenes")' + d, function (respuesta) {
            $('#listaOrdenes').html(respuesta);
        });
        
    });
</script>

ingInventario/Views/OrdenEntradas/OrdenEntrada.cshtml
@{
    ViewBag.Title = "Orden Entrada";
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox-title">
                <h3>Ingrese los datos para agregar productos al stock</h3>
            </div>
            <div class="ibox-content">
                <div class="form-group row">
                    <label class="col-sm-1">N° Factura</label>
                    <div class="col-sm-2">
                        <input type="text" id="numFact" class="form-control" />
                    </div>
                    <label class="col-sm-1">Comentario</label>
                    <div class="col-sm-4">
                        <input type="text" id="comentario"  class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-1">Código:</label>
                    <div class="col-sm-2" style="padding-right:0px">
                        <input type="text" class="form-control" id="codigo"/>
                    </div>
                    <div class="col-sm-3" style="padding-left:0px;padding-right:0px">
                        <input type="text" class="form-control" id="nombre" readonly/>
                    </div>
                    <label class="col-sm-1"> Cantidad:</label>
                    <div class="col-sm-1">
                        <input type="number" class="form-control solonumeros" id="cantidad"/>
                    </div>
                    <input type="button" id="agregar" value="Agregar" class="btn btn-primary"/>
                </div>
                <div id="tablaProductos" hidden>
                    <hr />
                    <div class="table-responsive">
                        <table id="detalleProducto" class="table">
                            <thead>
                                <tr class="bg-primary">
                                    <th>Código</th>
                                    <th>Nombre</th>
                                    <th>Cantidad</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                    <input type="button" id="guardar" value="Guardar" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/plugins/sweetalert/sweetalert.min.js"></script>
<script>
    $('.solonumeros').on('input', function () {
        this.value = this.value.replace(/[^0-9]/g, '');
    });
    let idProducto = 0;
    let datos = [];//arreglo para guardar los productos que se vayan agregando
    //ingresando código verifica si el producto existe, trae id_producto y nombre producto 
    $('#codigo').blur(function () {
        if ($('#codigo').val().trim() !== '') {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("CodigoExiste")',
                data: '{codigo:' + JSON.stringify($('#codigo').val()) + '}',
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (respuesta) {
                    if (respuesta !== '') {
                        $('#nombre').val(respuesta.nombre);
                        idProducto = respuesta.id_producto;
                    }
                }
            });
        }
    });
    $('#guardar').click(function () {
        //validación de datos
        let error = '';
        if ($('#numFact').val() == '')
            error = 'Debe ingresar número de factura \n';
        if (datos.length == 0)
            error += 'Debe agregar productos';
        if (error != '')
            swal('Error', error, 'warning');
        else {
            const ordenEntrada = {
                num_factura: $('#numFact').val(),
                comentario: $('#comentario').val()
            }
            $.ajax({
                type: 'POST',
                url: '@Url.Action("OrdenEntrada")',
                data: '{orden:' + JSON.stringify(ordenEntrada) + ',detalles:' + JSON.stringify(datos) + '}',
                dataType: 'json',
                contentType: 'application/json;charset=utf-8',
                success: function (resp) {
                    if (resp == '') {
                        swal({
                            title: 'Ingreso',
                            text: 'Los datos se han guardado con éxito!',
                            icon: 'success',
                            button: 'Cerrar',
                            closeOnClickOutside: false,
                        }).then(function (isConfirm) {
                            if (isConfirm) {
                                location.reload();//recarga la página                               
                            }
                        });
                    }
                }

            });
        }                
    });
    //*****TABLA DE PRODUCTOS*****//
    //agregar productos al arreglo
    $('#agregar').click(function () {
        //validación que verifica si los datos requeridos están ingresados
        let error = '';
        if ($('#nombre').val().trim() == '')
            error = 'Debe ingresar un producto \n';
        if ($('#cantidad').val() <= 0)
            error += 'Debe ingresar cantidad del producto';
        if (error != '')
            swal('Error', error, 'warning');
        else {
            //creamos un formato para asignarle los valores al arreglo
            const modelo = {
                id_producto: idProducto,
                codigo: $('#codigo').val(),
                nombre: $('#nombre').val(),
                cantidad: $('#cantidad').val()
            };
            //Pregunta si el arreglo tiene datos
            let x = 0;
            //verifica si el arreglo datos contiene algun producto o no
            if (datos.length > 0) {
                //si tiendas reccore el arreglo para verificar si el producto existe en el arreglo
                for (let i = 0; i < datos.length; i++) {
                    if (datos[i].id_producto == modelo.idProducto) {
                        datos[i].cantidad = modelo.cantidad;
                        x = 1;
                        break;//corta el ciclo
                    }
                }
                if (x == 0) {
                    datos.push(modelo);
                }
            }
            else {
                datos.push(modelo);//push sirve para añidir el modelo al arreglo ded datos
            }
            $('#tablaProductos').removeAttr('hidden', true);
            cargarTablaDetalle();//función que sirve para mostrar los datos del arreglo en una tabla
            limpiar();//función para limpiar los datos del producto ingresado
        }
        //función para cargar los productos del arreglo en una tabla 
        function cargarTablaDetalle() {
            $('#detalleProducto tbody').empty();//limpia el cuerpo de la tabla
            for (let i = 0; i < datos.length; i++) {//for para recorrer el arreglo y generar las filas de la tabla
                fila = '<tr>';
                fila += '<td>' + datos[i].codigo + '</td>';
                fila += '<td>' + datos[i].nombre + '</td>';
                fila += '<td>' + datos[i].cantidad + '</td>';
                fila += "<td><button class='btn btn-danger eliminar'><span class='fa fa-trash'></span></button>";
                fila += '</tr>';
                $('#detalleProducto tbody').append(fila);//mustra las filas en la tabla
                eliminar();//función que permite eliminar de la tabla y del arreglo datos
            }
        }
        //limpiar los datos del producto ingresado
        function limpiar() {
            idProducto = 0;
            $('#nombre').val('');
            $('#cantidad').val('');
            $('#codigo').val('');
        }
        //elimianr datos del arreglo y de la tabla
        function eliminar() {
            $('.eliminar').click(function () {

                //obtener el código de la fila donde se presiona el botón de trash 
                let cod = $(this).parents('tr').find('td').eq(0).html();
                for (let i = 0; i < datos.length; i++) {
                    if (datos[i].codigo == cod) {
                        datos.splice(i, 1);//splice sirve para sacar elementos del arreglo
                    }
                }
                //llamar a función cargar tabla para recargar el arreglo en la tabla 
                cargarTablaDetalle();
                //si la cantidad de elementos que hay en la tabla es == 0 la oculta
                if (datos.length == 0) {
                    $('#tablaProductos').attr('hidden',true);
                }
            });
        }
        //*****FIN TABLA DE PRODUCTOS*****//
    });
</script>

ingInventario/Views/OrdenEntradas/_Ordenes.cshtml
<div class="table-responsive">
    <table class="table table-striped table-bordered " id="tabla">
        <thead>
            <tr>
                <th>Número Factura</th>
                <th>Comentario</th>
                <th>Usuario Ingreso</th>
                <th>Fecha Ingreso</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.num_factura</td>
                    <td>@item.comentario</td>
                    <td>@item.Usuario.nombre</td>
                    <td>@item.fecha.ToShortDateString()</td>
                    <td style="white-space: nowrap">
                        <a href="@Url.Action("DetalleOrden","OrdenEntradas",new { id = item.id_orden })" target="_blank" class="btn btn-warning">
                            <i class="fa fa-list"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>